apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-uri
data:
  mongo_uri: {{ required "A valid .Values.mongo_uri  entry required!" .Values.mongo_uri | b64enc }}
  nats_uri: {{ required "A valid  .Values.nats_uri entry required!" .Values.nats_uri | b64enc }}