apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-queries
  labels:
    {{- include "sideralis-core.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sideralis-core.name" . }}-queries
    app.kubernetes.io/instance: {{ .Release.Name }}-queries
